export type MenuCategory = "main" | "tapas" | "salad" | "dessert" | "drink";
export type MenuStatus = "active" | "coming-soon";

export type MenuItem = {
  id: string;
  category: MenuCategory;
  priceWon?: number;
  option?: { labelKo: string; labelEn: string; priceWon: number };
  status: MenuStatus;
  featured?: boolean;
  needsReview?: boolean;
  ko: { name: string; description?: string; ingredients?: string };
  en: { name: string; description?: string; ingredients?: string };
};

export const categories: MenuCategory[] = ["main", "tapas", "salad", "dessert", "drink"];

export const menuItems: MenuItem[] = [
  { id:"abalone-paella", category:"main", priceWon:34000, status:"active", featured:true, ko:{name:"전복 빠에야",description:"(2~2.5인분) 완도 전복으로 깊은 바다 향을 담은 리오리오 시그니처 빠에야",ingredients:"완도 전복 · 신동진 쌀 · 새우 · 오징어"}, en:{name:"Abalone Paella",description:"RIORIO’s signature paella for 2–2.5, infused with the deep ocean flavor of Wando abalone.",ingredients:"Wando abalone · Sindongjin rice · Shrimp · Squid"}},
  { id:"iberico-steak", category:"main", priceWon:34000, status:"active", ko:{name:"베요타 100% 이베리코 스테이크",description:"도토리만 먹고 자란 스페인 흑돼지 이베리코를 수비드로 부드럽게 조리해 구운 꽃목살 스테이크",ingredients:"이베리코 베요타 꽃목살 · 감자 퓌레 · 사과 퓌레"}, en:{name:"100% Bellota Ibérico Steak",description:"Tender sous-vide and grilled collar steak from acorn-fed Spanish Ibérico pork.",ingredients:"Ibérico Bellota collar · Potato purée · Apple purée"}},
  { id:"pulpo", category:"main", priceWon:36000, status:"active", featured:true, ko:{name:"뽈뽀 아 라 가예가",description:"콩피 기법으로 조리하고 200시간 숙성으로 부드러움의 끝을 보여주는 갈리시아식 문어 요리",ingredients:"문어 · 감자 · 스피니치 · 토마토"}, en:{name:"Pulpo a la Gallega",description:"Galician-style octopus, confit-cooked and aged for 200 hours for exceptional tenderness.",ingredients:"Octopus · Potato · Spinach · Tomato"}},
  { id:"honey-cod", category:"main", priceWon:29000, status:"active", ko:{name:"꿀대구",description:"스페인식 라따뚜이 위에 얹은 대구살과 꿀, 아이올리 소스를 직화해 향을 끌어올린 꿀대구",ingredients:"대구 · 삐스또 · 아이올리 · 꿀"}, en:{name:"Honey Cod",description:"Flame-finished cod with honey and aioli, served over Spanish pisto.",ingredients:"Cod · Pisto · Aioli · Honey"}},
  { id:"tortilla", category:"main", priceWon:21000, status:"active", featured:true, ko:{name:"또르띠야 에스파뇰라",description:"(2~3인분) 감자와 달걀을 천천히 익혀 만든 스페인 가정식 오믈렛",ingredients:"감자 · 달걀 · 스피니치 · 양파 · 이베리코 베요타 판체타"}, en:{name:"Tortilla Española",description:"A homestyle Spanish omelet for 2–3, made by slowly cooking potato and egg.",ingredients:"Potato · Egg · Spinach · Onion · Ibérico Bellota pancetta"}},
  { id:"iberico-stew", category:"main", status:"coming-soon", ko:{name:"이베리코 스튜",description:"부드럽게 푹 익힌 이베리코와 채소를 깊고 진한 토마토 소스로 끓여낸 스페인식 스튜",ingredients:"이베리코 베요타 · 토마토 · 신선한 채소"}, en:{name:"Ibérico Stew",description:"Slow-cooked Ibérico and vegetables in a deep, rich tomato sauce.",ingredients:"Ibérico Bellota · Tomato · Fresh vegetables"}},
  { id:"albondigas", category:"main", status:"coming-soon", ko:{name:"알본디가스",description:"촉촉한 미트볼을 진한 스페인식 라따뚜이인 삐스또와 함께 곁들여 먹는 미트볼 요리",ingredients:"국내산 돼지고기 · 소고기 · 루꼴라 · 삐스또"}, en:{name:"Albóndigas",description:"Juicy meatballs served with rich Spanish pisto.",ingredients:"Korean pork · Beef · Arugula · Pisto"}},
  { id:"gambas", category:"tapas", priceWon:18000, status:"active", featured:true, ko:{name:"감바스 알 아히요",description:"새우와 마늘을 콩피하여 향을 끌어올린 오일에 순두부떡을 곁들여 먹는 스페인 타파스",ingredients:"새우 · 순두부 · 마늘 콩피 · 엑스트라 버진 올리브오일"}, en:{name:"Gambas al Ajillo",description:"Spanish tapas of shrimp and garlic confit oil, served with soft-tofu rice cake.",ingredients:"Shrimp · Soft tofu · Garlic confit · Extra virgin olive oil"}},
  { id:"patatas-bravas", category:"tapas", status:"coming-soon", ko:{name:"타파파스 브라바스",description:"바삭하게 튀긴 감자에 매콤한 살사 브라바 소스와 부드러운 아이올리를 곁들인 스페인 대표 타파스.",ingredients:"감자 · 살사 브라바 · 아이올리"}, en:{name:"Patatas Bravas",description:"Crispy potatoes with spicy salsa brava and smooth aioli.",ingredients:"Potato · Salsa brava · Aioli"}},
  { id:"croquetas", category:"tapas", priceWon:6000, option:{labelKo:"5pcs",labelEn:"5 pcs",priceWon:9000}, status:"active", ko:{name:"새우 크로케타스",description:"새우와 베샤멜을 바삭하게 튀긴 스페인식 한 입 크로케타스 · 3pcs",ingredients:"새우 베샤멜"}, en:{name:"Shrimp Croquetas",description:"Crispy Spanish bite-size croquetas with shrimp béchamel · 3 pcs",ingredients:"Shrimp béchamel"}},
  { id:"champinones", category:"tapas", priceWon:15000, status:"active", ko:{name:"참피뇨네스",description:"양송이 버섯과 생크림으로 만든 소스를 더해 버섯의 풍미를 끌어낸 특등급 양송이 구이 · 7pcs",ingredients:"특양송이 · 팽이버섯 · 이베리코 베요타 판체타 · 크림소스 · 블랙 트러플 오일"}, en:{name:"Champiñones",description:"Premium grilled mushrooms with a rich mushroom and cream sauce · 7 pcs",ingredients:"Mushrooms · Enoki · Ibérico Bellota pancetta · Cream sauce · Black truffle oil"}},
  { id:"calamares", category:"tapas", priceWon:14000, status:"active", featured:true, ko:{name:"깔라마레스 프리또스",description:"오징어 먹물 반죽으로 튀긴 마드리드식 오징어 튀김",ingredients:"오징어 · 오징어 먹물 · 아이올리 · 레몬"}, en:{name:"Calamares Fritos",description:"Madrid-style calamari fried in squid-ink batter.",ingredients:"Squid · Squid ink · Aioli · Lemon"}},
  { id:"honey-eggplant", category:"tapas", priceWon:12000, status:"active", featured:true, ko:{name:"꿀가지 튀김",description:"가지를 튀겨 리오리오만의 꿀 소스를 곁들여서 먹는 주인장 최애 타파스",ingredients:"가지 · 꿀 · 화이트 발사믹"}, en:{name:"Honey-Fried Eggplant",description:"The owner’s favorite: fried eggplant with RIORIO’s honey sauce.",ingredients:"Eggplant · Honey · White balsamic"}},
  { id:"baked-eggplant", category:"tapas", priceWon:19000, status:"active", ko:{name:"스페인식 가지 구이",description:"스페인식 라구소스로 속을 채운 가정식 가지 구이",ingredients:"가지 · 스페인식 라구소스 · 토마토 · 파프리카 · 모짜렐라 · 루꼴라"}, en:{name:"Spanish Baked Eggplant",description:"Homestyle baked eggplant filled with Spanish ragù.",ingredients:"Eggplant · Spanish ragù · Tomato · Paprika · Mozzarella · Arugula"}},
  { id:"burrata", category:"salad", priceWon:18000, status:"active", featured:true, ko:{name:"부라타 치즈 샐러드",description:"신선한 부라타 치즈와 화이트 발사믹 식초, 화이트 트러플 오일 마늘 드레싱을 더한 샐러드",ingredients:"부라타 치즈 · 루꼴라 · 세모가사리 · 바다포도 · 화이트 트러플 오일 · 화이트 발사믹"}, en:{name:"Burrata Cheese Salad",description:"Fresh burrata with white balsamic and a white-truffle garlic dressing.",ingredients:"Burrata · Arugula · Seaweed · Sea grapes · White truffle oil · White balsamic"}},
  { id:"ensaladilla", category:"salad", priceWon:5000, status:"active", featured:true, ko:{name:"엔살라다 루사",description:"감자와 채소를 고소한 마요 베이스로 버무린 스페인식 샐러드",ingredients:"감자 · 계란 · 참치 · 채소"}, en:{name:"Ensaladilla Rusa",description:"Spanish potato and vegetable salad in a savory mayonnaise dressing.",ingredients:"Potato · Egg · Tuna · Vegetables"}},
  { id:"cheesecake", category:"dessert", priceWon:10000, option:{labelKo:"빵 추가 · 5pcs",labelEn:"Extra bread · 5 pcs",priceWon:2500}, status:"active", ko:{name:"블루베리 바스크 치즈케이크",description:"스페인 북부식 바스크 치즈케이크 위에 와인향을 입힌 수제 블루베리 잼",ingredients:"생크림 · 계란 · 크림치즈 · 블루베리 · 레드와인"}, en:{name:"Blueberry Basque Cheesecake",description:"Northern Spanish Basque cheesecake topped with house-made, wine-infused blueberry jam.",ingredients:"Cream · Egg · Cream cheese · Blueberry · Red wine"}},
  { id:"sangria-bottle", category:"drink", priceWon:39000, status:"active", ko:{name:"샹그리아 바틀",description:"레드와인 베이스에 과일을 숙성해 향을 끌어올린 스페인 대표 와인 칵테일",ingredients:"라임 · 레몬 · 오렌지 · 사과 · 스페인 브랜디"}, en:{name:"Sangria Bottle",description:"Spain’s classic wine cocktail, made by infusing fruit in a red-wine base.",ingredients:"Lime · Lemon · Orange · Apple · Spanish brandy"}},
  { id:"sangria-glass", category:"drink", priceWon:9000, status:"active", ko:{name:"샹그리아 글라스",description:"레드와인 베이스에 과일을 숙성해 향을 끌어올린 스페인 대표 와인 칵테일",ingredients:"라임 · 레몬 · 오렌지 · 사과 · 스페인 브랜디"}, en:{name:"Sangria Glass",description:"Spain’s classic wine cocktail, made by infusing fruit in a red-wine base.",ingredients:"Lime · Lemon · Orange · Apple · Spanish brandy"}},
  { id:"estrella", category:"drink", priceWon:8000, status:"active", featured:true, ko:{name:"바르셀로나 에스트렐라 담 생맥주",description:"스페인 바르셀로나 대표 맥주, 기분 좋은 탄산감과 은은한 곡물 향, 입안에서는 깔끔한 라거 본연의 맛"}, en:{name:"Barcelona Estrella Damm Draft",description:"Barcelona’s signature beer with lively carbonation, subtle grain aromas, and a clean lager finish."}},
  { id:"house-wine", category:"drink", priceWon:6000, status:"active", ko:{name:"하우스 와인 (레드 or 화이트)",description:"레드는 부드러운 과실감, 화이트는 산뜻한 산미로 가볍게 즐기기 좋은 데일리 와인"}, en:{name:"House Wine (Red or White)",description:"An easy-drinking daily wine: soft fruit in the red, bright acidity in the white."}},
  { id:"sparkling-water", category:"drink", priceWon:2000, status:"active", ko:{name:"탄산수"}, en:{name:"Sparkling Water"}},
  { id:"soft-drink", category:"drink", priceWon:2000, status:"active", ko:{name:"음료",description:"펩시제로, 코카콜라, 스프라이트"}, en:{name:"Soft Drink",description:"Pepsi Zero, Coca-Cola, Sprite"}},
];
