import type { MenuItem } from "./data";
import type { MenuCopy } from "./translations";
const ids=["abalone-paella","iberico-steak","pulpo","honey-cod","tortilla","iberico-stew","albondigas","gambas","patatas-bravas","croquetas","champinones","calamares","honey-eggplant","baked-eggplant","burrata","ensaladilla","cheesecake","sangria-bottle","sangria-glass","estrella","house-wine","sparkling-water","soft-drink"];
type Pair=[string,string];
const build=(items:MenuItem[],pairs:Pair[])=>Object.fromEntries(ids.map((id,i)=>{const item=items.find(x=>x.id===id)!;return[id,{name:pairs[i][0],description:pairs[i][1],ingredients:item.en.ingredients,option:item.option?.labelEn}]})) as Record<string,MenuCopy>;

const th:Pair[]=[
["ปาเอยาอะบาโลนซิกเนเจอร์","ปาเอยาซิกเนเจอร์สำหรับ 2–2.5 ท่าน หอมรสทะเลลึกจากอะบาโลนวานโด"],["สเต๊กอิเบริโก เบโยตา 100%","เนื้อคอหมูอิเบริโกเลี้ยงด้วยลูกโอ๊ก ซูวีดจนนุ่มแล้วนำไปย่าง"],["Pulpo a la Gallega","ปลาหมึกยักษ์แบบกาลิเซีย ปรุงคอนฟีและบ่ม 200 ชั่วโมงจนนุ่ม"],["ปลาค็อดน้ำผึ้ง","ปลาค็อดบนพิสโต ราดน้ำผึ้งและไอโอลี แล้วจบด้วยไฟ"],["Tortilla Española","ออมเล็ตสเปนแบบโฮมเมดสำหรับ 2–3 ท่าน จากมันฝรั่งและไข่ที่ปรุงช้า ๆ"],["สตูว์อิเบริโก","หมูอิเบริโกและผักเคี่ยวช้าในซอสมะเขือเทศเข้มข้น"],["Albóndigas","มีตบอลฉ่ำเสิร์ฟกับพิสโตสเปนรสเข้ม"],["Gambas al Ajillo","กุ้งและกระเทียมคอนฟี เสิร์ฟกับเค้กเต้าหู้นุ่ม"],["Patatas Bravas","มันฝรั่งกรอบกับซอสบราวารสเผ็ดและไอโอลีนุ่ม"],["คร็อกเกตกุ้ง","คร็อกเกตเบชาเมลกุ้งทอดกรอบ 3 ชิ้น"],["Champiñones","เห็ดคัดพิเศษกับซอสครีมเห็ด 7 ชิ้น"],["Calamares Fritos","ปลาหมึกทอดสไตล์มาดริดในแป้งหมึกดำ"],["มะเขือม่วงทอดน้ำผึ้ง","มะเขือม่วงทอดกับซอสน้ำผึ้งสูตร RIORIO"],["มะเขือม่วงอบสเปน","มะเขือม่วงอบแบบโฮมเมดสอดไส้รากูสเปน"],["สลัดบูราตา","บูราตาสดกับบัลซามิกขาวและเดรสซิงกระเทียมทรัฟเฟิลขาว"],["Ensaladilla Rusa","สลัดมันฝรั่งและผักแบบสเปนคลุกมายองเนส"],["บาสก์ชีสเค้กบลูเบอร์รี","บาสก์ชีสเค้กกับแยมบลูเบอร์รีไวน์ทำเอง"],["ซังเกรียขวด","ค็อกเทลสเปนจากไวน์แดงและผลไม้หมัก"],["ซังเกรียแก้ว","ค็อกเทลสเปนจากไวน์แดงและผลไม้หมัก"],["เอสเตรยา ดัมม์ สด","ลาเกอร์จากบาร์เซโลนาที่ซ่าสดชื่น หอมธัญพืชและจบสะอาด"],["เฮาส์ไวน์ แดงหรือขาว","ไวน์แดงนุ่มหอมผลไม้ หรือไวน์ขาวสดชื่น"],["น้ำแร่มีฟอง","น้ำแร่มีฟองเย็นสดชื่น"],["น้ำอัดลม","เป๊ปซี่ซีโร่ โคคา-โคลา สไปรท์"]];
const vi:Pair[]=[
["Paella bào ngư Signature","Paella đặc trưng cho 2–2,5 người với vị biển sâu từ bào ngư Wando"],["Bít tết Ibérico Bellota 100%","Thịt cổ heo Ibérico ăn hạt sồi, nấu sous-vide mềm rồi nướng"],["Pulpo a la Gallega","Bạch tuộc kiểu Galicia nấu confit và ủ 200 giờ cho độ mềm đặc biệt"],["Cá tuyết mật ong","Cá tuyết trên pisto với mật ong và aioli, hoàn thiện trên lửa"],["Tortilla Española","Trứng tráng Tây Ban Nha cho 2–3 người với khoai tây và trứng nấu chậm"],["Hầm Ibérico","Thịt heo Ibérico và rau củ hầm chậm trong sốt cà chua đậm đà"],["Albóndigas","Thịt viên mọng nước dùng cùng pisto Tây Ban Nha đậm vị"],["Gambas al Ajillo","Tôm và tỏi confit, dùng cùng bánh đậu phụ mềm"],["Patatas Bravas","Khoai tây giòn với sốt brava cay và aioli mượt"],["Croquetas tôm","Croquetas béchamel tôm giòn, 3 miếng"],["Champiñones","Nấm tuyển chọn với sốt kem nấm, 7 miếng"],["Calamares Fritos","Mực chiên kiểu Madrid với bột mực đen"],["Cà tím chiên mật ong","Cà tím chiên với sốt mật ong riêng của RIORIO"],["Cà tím nướng kiểu Tây Ban Nha","Cà tím nướng nhà làm nhồi ragù Tây Ban Nha"],["Salad burrata","Burrata tươi với giấm balsamic trắng và sốt tỏi nấm truffle trắng"],["Ensaladilla Rusa","Salad khoai tây và rau củ kiểu Tây Ban Nha với mayonnaise"],["Bánh phô mai Basque việt quất","Bánh phô mai Basque với mứt việt quất ngâm rượu nhà làm"],["Sangria chai","Cocktail Tây Ban Nha từ rượu vang đỏ và trái cây ngâm"],["Sangria ly","Cocktail Tây Ban Nha từ rượu vang đỏ và trái cây ngâm"],["Bia tươi Estrella Damm","Lager Barcelona sảng khoái, thơm ngũ cốc và hậu vị sạch"],["Vang nhà đỏ hoặc trắng","Vang đỏ mềm, vị trái cây hoặc vang trắng tươi sáng"],["Nước có ga","Nước khoáng có ga mát lạnh"],["Nước ngọt","Pepsi Zero, Coca-Cola, Sprite"]];
const id:Pair[]=[
["Signature Abalone Paella","Paella khas untuk 2–2,5 orang dengan cita rasa laut abalone Wando"],["Steak Ibérico Bellota 100%","Leher babi Ibérico pemakan biji ek, dimasak sous-vide hingga empuk lalu dipanggang"],["Pulpo a la Gallega","Gurita gaya Galicia, dimasak confit dan dimatangkan 200 jam"],["Kod madu","Ikan kod di atas pisto dengan madu dan aioli, diselesaikan di atas api"],["Tortilla Española","Omelet rumahan Spanyol untuk 2–3 orang dari kentang dan telur yang dimasak perlahan"],["Semur Ibérico","Babi Ibérico dan sayuran dimasak perlahan dalam saus tomat kaya rasa"],["Albóndigas","Bakso berair disajikan dengan pisto Spanyol yang kaya"],["Gambas al Ajillo","Udang dan bawang putih confit dengan kue tahu lembut"],["Patatas Bravas","Kentang renyah dengan salsa brava pedas dan aioli lembut"],["Croquetas udang","Croquetas renyah berisi béchamel udang, 3 buah"],["Champiñones","Jamur pilihan dengan saus krim jamur, 7 buah"],["Calamares Fritos","Cumi goreng gaya Madrid dengan adonan tinta cumi"],["Terung goreng madu","Terung goreng dengan saus madu khas RIORIO"],["Terung panggang Spanyol","Terung panggang rumahan berisi ragù Spanyol"],["Salad burrata","Burrata segar dengan balsamik putih dan saus bawang putih-truffle putih"],["Ensaladilla Rusa","Salad kentang dan sayuran ala Spanyol dengan mayones"],["Basque cheesecake blueberry","Basque cheesecake dengan selai blueberry anggur buatan rumah"],["Sangria botol","Koktail Spanyol dari anggur merah dan buah yang dimaserasi"],["Sangria gelas","Koktail Spanyol dari anggur merah dan buah yang dimaserasi"],["Estrella Damm draft","Lager Barcelona dengan karbonasi segar, aroma biji-bijian, dan akhir bersih"],["House wine merah atau putih","Merah lembut dan berbuah atau putih segar"],["Air berkarbonasi","Air mineral berkarbonasi"],["Minuman ringan","Pepsi Zero, Coca-Cola, Sprite"]];
const ms:Pair[]=[
["Paella Abalon Signature","Paella istimewa untuk 2–2.5 orang dengan rasa laut abalon Wando"],["Stik Ibérico Bellota 100%","Leher khinzir Ibérico pemakan buah oak, dimasak sous-vide hingga lembut lalu dipanggang"],["Pulpo a la Gallega","Sotong kurita gaya Galicia, dimasak confit dan diperam 200 jam"],["Ikan kod madu","Ikan kod di atas pisto dengan madu dan aioli, disiapkan dengan api"],["Tortilla Española","Omelet Sepanyol rumahan untuk 2–3 orang daripada kentang dan telur yang dimasak perlahan"],["Stu Ibérico","Khinzir Ibérico dan sayuran direneh dalam sos tomato yang kaya"],["Albóndigas","Bebola daging berjus dengan pisto Sepanyol yang kaya"],["Gambas al Ajillo","Udang dan bawang putih confit bersama kek tauhu lembut"],["Patatas Bravas","Kentang rangup dengan salsa brava pedas dan aioli lembut"],["Croquetas udang","Croquetas rangup berisi béchamel udang, 3 keping"],["Champiñones","Cendawan terpilih dengan sos krim cendawan, 7 keping"],["Calamares Fritos","Sotong goreng gaya Madrid dengan adunan dakwat sotong"],["Terung goreng madu","Terung goreng dengan sos madu khas RIORIO"],["Terung bakar Sepanyol","Terung bakar rumahan berinti ragù Sepanyol"],["Salad burrata","Burrata segar dengan balsamik putih dan sos bawang putih-trufel putih"],["Ensaladilla Rusa","Salad kentang dan sayuran Sepanyol dengan mayonis"],["Kek keju Basque beri biru","Kek keju Basque dengan jem beri biru beraroma wain buatan sendiri"],["Sangria botol","Koktel Sepanyol daripada wain merah dan buah perapan"],["Sangria gelas","Koktel Sepanyol daripada wain merah dan buah perapan"],["Estrella Damm draf","Lager Barcelona yang segar, beraroma bijirin dan berakhir bersih"],["Wain rumah merah atau putih","Merah lembut berbuah atau putih yang segar"],["Air berkarbonat","Air mineral berkarbonat"],["Minuman ringan","Pepsi Zero, Coca-Cola, Sprite"]];

export const extendedMenuPart1=(items:MenuItem[])=>({th:build(items,th),vi:build(items,vi),id:build(items,id),ms:build(items,ms)});
