export const supportedLocales = ["ko","en","ja","zh-CN","zh-TW","es","es-419","fr","pt","pt-BR","de","it","hi","th","vi","id","ms","ru","ar","tr","nl","pl","sv","da","no","fil"] as const;
export type MenuLocale = typeof supportedLocales[number];

export const languageNames: Record<MenuLocale,string> = { ko:"한국어",en:"English",ja:"日本語","zh-CN":"简体中文","zh-TW":"繁體中文",es:"Español","es-419":"Español Latinoamérica",fr:"Français",pt:"Português","pt-BR":"Português Brasileiro",de:"Deutsch",it:"Italiano",hi:"हिन्दी",th:"ไทย",vi:"Tiếng Việt",id:"Bahasa Indonesia",ms:"Bahasa Melayu",ru:"Русский",ar:"العربية",tr:"Türkçe",nl:"Nederlands",pl:"Polski",sv:"Svenska",da:"Dansk",no:"Norsk",fil:"Filipino" };

type Ui = { globalMenu:string; language:string; recommended:string; all:string; close:string; categories:Record<string,string>; coming:string; ingredients:string; notice:string; review:string };
const en: Ui = {globalMenu:"Global Menu",language:"Language",recommended:"Recommended",all:"All Languages",close:"Close",categories:{main:"Main Dish",tapas:"Tapas",salad:"Salad",dessert:"Dessert",drink:"Drink"},coming:"Coming Soon",ingredients:"Ingredients",notice:"Some ingredients may change depending on availability.",review:"Price pending confirmation"};
const partial: Record<MenuLocale,Partial<Ui>> = {
 ko:{globalMenu:"글로벌 메뉴",language:"언어",recommended:"추천 언어",all:"모든 언어",close:"닫기",categories:{main:"메인 디시",tapas:"타파스",salad:"샐러드",dessert:"디저트",drink:"음료"},coming:"출시 예정",ingredients:"재료",notice:"재료 수급 상황에 따라 일부 변경될 수 있습니다.",review:"가격 확인 중"},
 en:{}, ja:{globalMenu:"グローバルメニュー",language:"言語",recommended:"おすすめ",all:"すべての言語",close:"閉じる",categories:{main:"メイン料理",tapas:"タパス",salad:"サラダ",dessert:"デザート",drink:"ドリンク"},coming:"近日登場",ingredients:"材料",notice:"仕入れ状況により一部の材料が変更になる場合があります。"},
 "zh-CN":{globalMenu:"全球菜单",language:"语言",recommended:"推荐",all:"所有语言",close:"关闭",categories:{main:"主菜",tapas:"西班牙小吃",salad:"沙拉",dessert:"甜点",drink:"饮品"},coming:"即将推出",ingredients:"配料",notice:"部分配料可能因供应情况而有所调整。"},
 "zh-TW":{globalMenu:"全球菜單",language:"語言",recommended:"推薦",all:"所有語言",close:"關閉",categories:{main:"主菜",tapas:"西班牙小吃",salad:"沙拉",dessert:"甜點",drink:"飲品"},coming:"即將推出",ingredients:"食材",notice:"部分食材可能因供應情況而有所調整。"},
 es:{globalMenu:"Menú global",language:"Idioma",recommended:"Recomendados",all:"Todos los idiomas",close:"Cerrar",categories:{main:"Platos principales",tapas:"Tapas",salad:"Ensaladas",dessert:"Postres",drink:"Bebidas"},coming:"Próximamente",ingredients:"Ingredientes",notice:"Algunos ingredientes pueden variar según disponibilidad."},
 "es-419":{globalMenu:"Menú global",language:"Idioma",recommended:"Recomendados",all:"Todos los idiomas",close:"Cerrar",categories:{main:"Platos principales",tapas:"Tapas",salad:"Ensaladas",dessert:"Postres",drink:"Bebidas"},coming:"Próximamente",ingredients:"Ingredientes"},
 fr:{globalMenu:"Menu international",language:"Langue",recommended:"Recommandées",all:"Toutes les langues",close:"Fermer",categories:{main:"Plats principaux",tapas:"Tapas",salad:"Salades",dessert:"Desserts",drink:"Boissons"},coming:"Bientôt",ingredients:"Ingrédients"},
 pt:{globalMenu:"Menu global",language:"Idioma",recommended:"Recomendados",all:"Todos os idiomas",close:"Fechar",categories:{main:"Pratos principais",tapas:"Tapas",salad:"Saladas",dessert:"Sobremesas",drink:"Bebidas"},coming:"Em breve",ingredients:"Ingredientes"},
 "pt-BR":{globalMenu:"Menu global",language:"Idioma",recommended:"Recomendados",all:"Todos os idiomas",close:"Fechar",categories:{main:"Pratos principais",tapas:"Tapas",salad:"Saladas",dessert:"Sobremesas",drink:"Bebidas"},coming:"Em breve",ingredients:"Ingredientes"},
 de:{globalMenu:"Globales Menü",language:"Sprache",recommended:"Empfohlen",all:"Alle Sprachen",close:"Schließen",categories:{main:"Hauptgerichte",tapas:"Tapas",salad:"Salate",dessert:"Desserts",drink:"Getränke"},coming:"Demnächst",ingredients:"Zutaten"},
 it:{globalMenu:"Menu globale",language:"Lingua",recommended:"Consigliate",all:"Tutte le lingue",close:"Chiudi",categories:{main:"Piatti principali",tapas:"Tapas",salad:"Insalate",dessert:"Dolci",drink:"Bevande"},coming:"Prossimamente",ingredients:"Ingredienti"},
 hi:{globalMenu:"वैश्विक मेनू",language:"भाषा",recommended:"सुझाई गई",all:"सभी भाषाएँ",close:"बंद करें",categories:{main:"मुख्य व्यंजन",tapas:"तापास",salad:"सलाद",dessert:"मिठाई",drink:"पेय"},coming:"जल्द आ रहा है",ingredients:"सामग्री"},
 ar:{globalMenu:"القائمة العالمية",language:"اللغة",recommended:"موصى بها",all:"جميع اللغات",close:"إغلاق",categories:{main:"الأطباق الرئيسية",tapas:"تاباس",salad:"السلطات",dessert:"الحلويات",drink:"المشروبات"},coming:"قريباً",ingredients:"المكونات",notice:"قد تتغير بعض المكونات حسب التوفر.",review:"يرجى التأكد من السعر"},
 th:{globalMenu:"เมนูสากล",language:"ภาษา",recommended:"แนะนำ",all:"ทุกภาษา",close:"ปิด",categories:{main:"อาหารจานหลัก",tapas:"ทาปาส",salad:"สลัด",dessert:"ของหวาน",drink:"เครื่องดื่ม"},coming:"เร็ว ๆ นี้",ingredients:"ส่วนประกอบ"},
 vi:{globalMenu:"Thực đơn toàn cầu",language:"Ngôn ngữ",recommended:"Đề xuất",all:"Tất cả ngôn ngữ",close:"Đóng",categories:{main:"Món chính",tapas:"Tapas",salad:"Salad",dessert:"Tráng miệng",drink:"Đồ uống"},coming:"Sắp ra mắt",ingredients:"Thành phần"},
 id:{globalMenu:"Menu global",language:"Bahasa",recommended:"Disarankan",all:"Semua bahasa",close:"Tutup",categories:{main:"Hidangan utama",tapas:"Tapas",salad:"Salad",dessert:"Hidangan penutup",drink:"Minuman"},coming:"Segera hadir",ingredients:"Bahan"},
 ms:{globalMenu:"Menu global",language:"Bahasa",recommended:"Disyorkan",all:"Semua bahasa",close:"Tutup",categories:{main:"Hidangan utama",tapas:"Tapas",salad:"Salad",dessert:"Pencuci mulut",drink:"Minuman"},coming:"Akan datang",ingredients:"Bahan-bahan"},
 ru:{globalMenu:"Международное меню",language:"Язык",recommended:"Рекомендуемые",all:"Все языки",close:"Закрыть",categories:{main:"Основные блюда",tapas:"Тапас",salad:"Салаты",dessert:"Десерты",drink:"Напитки"},coming:"Скоро",ingredients:"Ингредиенты"},
 tr:{globalMenu:"Global menü",language:"Dil",recommended:"Önerilen",all:"Tüm diller",close:"Kapat",categories:{main:"Ana yemekler",tapas:"Tapas",salad:"Salatalar",dessert:"Tatlılar",drink:"İçecekler"},coming:"Yakında",ingredients:"İçindekiler"},
 nl:{globalMenu:"Wereldmenu",language:"Taal",recommended:"Aanbevolen",all:"Alle talen",close:"Sluiten",categories:{main:"Hoofdgerechten",tapas:"Tapas",salad:"Salades",dessert:"Desserts",drink:"Dranken"},coming:"Binnenkort",ingredients:"Ingrediënten"},
 pl:{globalMenu:"Menu globalne",language:"Język",recommended:"Polecane",all:"Wszystkie języki",close:"Zamknij",categories:{main:"Dania główne",tapas:"Tapas",salad:"Sałatki",dessert:"Desery",drink:"Napoje"},coming:"Wkrótce",ingredients:"Składniki"},
 sv:{globalMenu:"Global meny",language:"Språk",recommended:"Rekommenderade",all:"Alla språk",close:"Stäng",categories:{main:"Huvudrätter",tapas:"Tapas",salad:"Sallader",dessert:"Desserter",drink:"Drycker"},coming:"Kommer snart",ingredients:"Ingredienser"},
 da:{globalMenu:"Global menu",language:"Sprog",recommended:"Anbefalede",all:"Alle sprog",close:"Luk",categories:{main:"Hovedretter",tapas:"Tapas",salad:"Salater",dessert:"Desserter",drink:"Drikkevarer"},coming:"Kommer snart",ingredients:"Ingredienser"},
 no:{globalMenu:"Global meny",language:"Språk",recommended:"Anbefalt",all:"Alle språk",close:"Lukk",categories:{main:"Hovedretter",tapas:"Tapas",salad:"Salater",dessert:"Desserter",drink:"Drikkevarer"},coming:"Kommer snart",ingredients:"Ingredienser"},
 fil:{globalMenu:"Pandaigdigang menu",language:"Wika",recommended:"Inirerekomenda",all:"Lahat ng wika",close:"Isara",categories:{main:"Pangunahing putahe",tapas:"Tapas",salad:"Salad",dessert:"Panghimagas",drink:"Inumin"},coming:"Malapit na",ingredients:"Mga sangkap"},
};
export const uiFor = (locale:MenuLocale):Ui => ({...en,...partial[locale],categories:{...en.categories,...partial[locale].categories}});
export const normalizeLocale = (raw?:string|null):MenuLocale => {
  if (!raw) return "en"; const exact=supportedLocales.find(x=>x.toLowerCase()===raw.toLowerCase()); if(exact) return exact;
  const base=raw.split("-")[0]; return supportedLocales.find(x=>x===base) ?? "en";
};
