create extension if not exists pgcrypto;

create table if not exists public.schedule_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '관리자',
  created_at timestamptz not null default now()
);

create table if not exists public.schedule_versions (
  id uuid primary key default gen_random_uuid(),
  week_start date not null,
  week_end date not null,
  version_label text not null,
  status text not null check (status in ('published', 'archived')),
  payload jsonb not null,
  published_at timestamptz not null default now(),
  published_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  constraint schedule_week_is_seven_days check (week_end = week_start + 6),
  constraint schedule_payload_is_object check (jsonb_typeof(payload) = 'object')
);

create unique index if not exists schedule_one_published_per_week
  on public.schedule_versions (week_start)
  where status = 'published';

create index if not exists schedule_versions_status_week_idx
  on public.schedule_versions (status, week_start desc);

create table if not exists public.schedule_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  action text not null,
  schedule_version_id uuid references public.schedule_versions(id),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.schedule_admins enable row level security;
alter table public.schedule_versions enable row level security;
alter table public.schedule_audit_logs enable row level security;

create or replace function public.is_schedule_admin(candidate uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.schedule_admins where user_id = candidate);
$$;

revoke all on function public.is_schedule_admin(uuid) from public;
grant execute on function public.is_schedule_admin(uuid) to authenticated;

drop policy if exists "published schedules are public" on public.schedule_versions;
create policy "published schedules are public"
  on public.schedule_versions for select
  to anon, authenticated
  using (status = 'published' or public.is_schedule_admin(auth.uid()));

drop policy if exists "admins can read own role" on public.schedule_admins;
create policy "admins can read own role"
  on public.schedule_admins for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "admins can read audit logs" on public.schedule_audit_logs;
create policy "admins can read audit logs"
  on public.schedule_audit_logs for select
  to authenticated
  using (public.is_schedule_admin(auth.uid()));

revoke insert, update, delete on public.schedule_versions from anon, authenticated;
revoke all on public.schedule_admins from anon;
revoke insert, update, delete on public.schedule_admins from authenticated;
revoke insert, update, delete on public.schedule_audit_logs from anon, authenticated;
grant select on public.schedule_versions to anon, authenticated;
grant select on public.schedule_admins to authenticated;
grant select on public.schedule_audit_logs to authenticated;

create or replace function public.publish_schedule_collection(p_schedules jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  new_id uuid;
  published_count integer := 0;
  start_date date;
  end_date date;
begin
  if auth.uid() is null or not public.is_schedule_admin(auth.uid()) then
    raise exception 'schedule admin access required' using errcode = '42501';
  end if;
  if jsonb_typeof(p_schedules) <> 'array' or jsonb_array_length(p_schedules) = 0 then
    raise exception 'at least one schedule is required';
  end if;

  for item in select value from jsonb_array_elements(p_schedules)
  loop
    start_date := (item #>> '{week,startDate}')::date;
    end_date := (item #>> '{week,endDate}')::date;
    if end_date <> start_date + 6 then raise exception 'invalid seven-day range: %', start_date; end if;
    if item->>'schemaVersion' <> '1' then raise exception 'unsupported schema version'; end if;
    if item #>> '{week,timeZone}' <> 'Asia/Seoul' then raise exception 'invalid timezone'; end if;
    if jsonb_array_length(coalesce(item->'employees', '[]'::jsonb)) = 0 then raise exception 'employees are required'; end if;
    if jsonb_array_length(coalesce(item->'dateStatuses', '[]'::jsonb)) <> jsonb_array_length(item->'employees') * 7 then raise exception 'date status coverage is incomplete'; end if;
    if exists(select 1 from jsonb_array_elements(item->'shifts') shift where shift->>'reviewStatus' <> 'reviewed') then raise exception 'unreviewed shift cannot be published'; end if;

    update public.schedule_versions set status = 'archived'
      where week_start = start_date and status = 'published';

    insert into public.schedule_versions (week_start, week_end, version_label, status, payload, published_by)
    values (start_date, end_date, item #>> '{week,version}', 'published', item, auth.uid())
    returning id into new_id;

    insert into public.schedule_audit_logs (actor_id, action, schedule_version_id, details)
    values (auth.uid(), 'publish', new_id, jsonb_build_object('weekStart', start_date));
    published_count := published_count + 1;
  end loop;
  return published_count;
end;
$$;

revoke all on function public.publish_schedule_collection(jsonb) from public, anon;
grant execute on function public.publish_schedule_collection(jsonb) to authenticated;

-- 최초 관리자 등록 예시:
-- insert into public.schedule_admins(user_id, display_name)
-- select id, '리오리오 매니저' from auth.users where email = 'manager@example.com';
